#!/usr/bin/env bash

# Reboot notifier
# Notifies via email when a reboot is required on a Debian based host 
#
# Author: James Loh (https://github.com/jloh/reboot-notifier)
#
# LICENSE
# MIT License
#
# Copyright (c) 2017 James Loh
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Binaries
_cat="$(which cat)"
_date="$(which date)"
_hostname="$(which hostname)"
_sendmail="$(which sendmail)"

# Variables
full_hostname="$($_hostname -f)"
reboot_file="/var/run/reboot-required"
reboot_packages_file="/var/run/reboot-required.pkgs"
reboot_packages_list=""
from_address="root@$full_hostname"
current_date="$($_date)"

function notify() {
		$_cat <<-EOF | $_sendmail root
		subject: Reboot required of host $full_hostname
		from: $from_address
		Auto-Submitted: auto-generated
		Precedence: bulk
		X-Reboot-Notifier: true

		*****  Warning  *****
 
Reboot required!

Host: $full_hostname
Date: $current_date

Packages requiring reboot:
$reboot_packages_list

		EOF
}

if [[ -e $reboot_packages_file ]]
then
	reboot_packages_list="$($_cat $reboot_packages_file)"
fi

if [[ -e $reboot_file ]]
then
	notify
fi
